In [13]:
import pandas as pd

df = pd.read_csv("../data/raw/diabetes_risk_prediction_dataset.csv")

In [14]:
df.shape

(50000, 41)

In [15]:
df.head()

,Patient_ID,Age,Gender,Country,Height_cm,Weight_kg,BMI,Waist_Circumference_cm,Blood_Glucose,HbA1c,...,Fatty_Liver,PCOS,Medication_Adherence,Work_Type,Residence_Type,Daily_Water_Intake_L,Diabetes_Risk_Score,AI_Health_Recommendation,Doctor_Consultation_Needed,Diabetes_Risk
0,1,32.0,Male,Mexico,182.1,65.8,19.8,71.2,88.4,10.4,...,Yes,No,Good,Retired,Rural,4.4,60,Healthy Diet Plan,Yes,Moderate
1,2,42.0,Other,Saudi Arabia,148.5,101.2,45.9,121.8,247.3,11.3,...,Yes,Yes,Average,Government,Rural,2.1,99,Begin Diabetes Management Plan,Yes,High
2,3,89.0,Other,Argentina,158.1,NaN,37.9,131.8,141.9,6.3,...,Yes,No,Average,Government,Urban,2.8,80,Strict Blood Sugar Monitoring,Yes,High
3,4,87.0,Other,United States,190.9,95.9,26.3,99.1,90.1,7.4,...,No,No,Average,Business,Rural,1.5,82,Begin Diabetes Management Plan,Yes,High
4,5,27.0,Other,Australia,156.9,101.9,41.4,77.1,93.8,12.0,...,Yes,Yes,Poor,Private,Rural,1.6,93,Begin Diabetes Management Plan,Yes,High

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 41 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Patient_ID                  50000 non-null  int64
 1   Age                         49503 non-null  float64
 2   Gender                      50000 non-null  str
 3   Country                     50000 non-null  str
 4   Height_cm                   47055 non-null  float64
 5   Weight_kg                   47038 non-null  float64
 6   BMI                         50000 non-null  float64
 7   Waist_Circumference_cm      50000 non-null  float64
 8   Blood_Glucose               49041 non-null  float64
 9   HbA1c                       48026 non-null  float64
 10  Fasting_Blood_Sugar         50000 non-null  float64
 11  Insulin_Level               50000 non-null  float64
 12  Blood_Pressure_Systolic     50000 non-null  int64
 13  Blood_Pressure_Diastolic    50000 non-null  int64
 14  Total_Cholesterol           49000 non-null  float64
 15  HDL                         49000 non-null  float64
 16  LDL                         49000 non-null  float64
 17  Triglycerides               49000 non-null  float64
 18  Heart_Rate                  50000 non-null  int64
 19  Physical_Activity_Level     49500 non-null  str
 20  Exercise_Hours_Per_Week     48008 non-null  float64
 21  Daily_Walking_Minutes       48036 non-null  float64
 22  Diet_Quality                50000 non-null  str
 23  Sugar_Intake_Level          50000 non-null  str
 24  Sleep_Hours                 47983 non-null  float64
 25  Stress_Level                50000 non-null  str
 26  Smoking_Status              50000 non-null  str
 27  Alcohol_Consumption         50000 non-null  str
 28  Family_History_Diabetes     50000 non-null  str
 29  Hypertension                50000 non-null  str
 30  Heart_Disease               50000 non-null  str
 31  Fatty_Liver                 50000 non-null  str
 32  PCOS                        50000 non-null  str
 33  Medication_Adherence        49000 non-null  str
 34  Work_Type                   50000 non-null  str
 35  Residence_Type              50000 non-null  str
 36  Daily_Water_Intake_L        50000 non-null  float64
 37  Diabetes_Risk_Score         50000 non-null  int64
 38  AI_Health_Recommendation    50000 non-null  str
 39  Doctor_Consultation_Needed  50000 non-null  str
 40  Diabetes_Risk               50000 non-null  str
dtypes: float64(17), int64(5), str(19)
memory usage: 15.6 MB

In [17]:
df.isnull().sum()

Patient_ID                       0
Age                            497
Gender                           0
Country                          0
Height_cm                     2945
Weight_kg                     2962
BMI                              0
Waist_Circumference_cm           0
Blood_Glucose                  959
HbA1c                         1974
Fasting_Blood_Sugar              0
Insulin_Level                    0
Blood_Pressure_Systolic          0
Blood_Pressure_Diastolic         0
Total_Cholesterol             1000
HDL                           1000
LDL                           1000
Triglycerides                 1000
Heart_Rate                       0
Physical_Activity_Level        500
Exercise_Hours_Per_Week       1992
Daily_Walking_Minutes         1964
Diet_Quality                     0
Sugar_Intake_Level               0
Sleep_Hours                   2017
Stress_Level                     0
Smoking_Status                   0
Alcohol_Consumption              0
Family_History_Diabetes          0
Hypertension                     0
Heart_Disease                    0
Fatty_Liver                      0
PCOS                             0
Medication_Adherence          1000
Work_Type                        0
Residence_Type                   0
Daily_Water_Intake_L             0
Diabetes_Risk_Score              0
AI_Health_Recommendation         0
Doctor_Consultation_Needed       0
Diabetes_Risk                    0
dtype: int64

In [18]:
df["Diabetes_Risk"].value_counts()

Diabetes_Risk
High        36593
Moderate    12937
Low           470
Name: count, dtype: int64

In [19]:
df[["Diabetes_Risk_Score", "Diabetes_Risk"]].groupby(
    "Diabetes_Risk"
).describe()

              Diabetes_Risk_Score                                          \
                            count       mean        std   min   25%   50%
Diabetes_Risk
High                      36593.0  81.409122  10.159132  65.0  73.0  81.0
Low                         470.0  29.236170   4.302225  13.0  27.0  30.0
Moderate                  12937.0  54.838912   7.248303  35.0  50.0  56.0


                75%    max
Diabetes_Risk
High           89.0  100.0
Low            33.0   34.0
Moderate       61.0   64.0

In [20]:
pd.crosstab(
    df["Doctor_Consultation_Needed"],
    df["Diabetes_Risk"],
    normalize="index"
)

Diabetes_Risk                   High       Low  Moderate
Doctor_Consultation_Needed
No                          0.000000  0.116676  0.883324
Yes                         0.788201  0.001142  0.210658

In [21]:
pd.crosstab(
    df["AI_Health_Recommendation"],
    df["Diabetes_Risk"],
    normalize="index"
)

Diabetes_Risk                        High  Low  Moderate
AI_Health_Recommendation
Annual Diabetes Screening             0.0  1.0       0.0
Balanced Diet                         0.0  1.0       0.0
Begin Diabetes Management Plan        1.0  0.0       0.0
Consult Endocrinologist Immediately   1.0  0.0       0.0
Exercise Regularly                    0.0  1.0       0.0
Healthy Diet Plan                     0.0  0.0       1.0
Immediate Lifestyle Intervention      1.0  0.0       0.0
Increase Physical Activity            0.0  0.0       1.0
Maintain Healthy Lifestyle            0.0  1.0       0.0
Medical Evaluation Required           1.0  0.0       0.0
Monitor Blood Glucose                 0.0  0.0       1.0
Reduce Sugar Intake                   0.0  0.0       1.0
Routine Health Checkup                0.0  1.0       0.0
Strict Blood Sugar Monitoring         1.0  0.0       0.0
Weight Management Program             0.0  0.0       1.0

In [22]:
df["AI_Health_Recommendation"].value_counts().head(20)

AI_Health_Recommendation
Strict Blood Sugar Monitoring          7481
Immediate Lifestyle Intervention       7419
Consult Endocrinologist Immediately    7271
Medical Evaluation Required            7230
Begin Diabetes Management Plan         7192
Weight Management Program              2616
Reduce Sugar Intake                    2615
Monitor Blood Glucose                  2582
Increase Physical Activity             2564
Healthy Diet Plan                      2560
Exercise Regularly                      113
Balanced Diet                           100
Routine Health Checkup                   91
Annual Diabetes Screening                86
Maintain Healthy Lifestyle               80
Name: count, dtype: int64

In [ ]:
drop_columns = [
    "Patient_ID",
    "Diabetes_Risk_Score",
    "AI_Healthy_Recommendation",
    "Doctor_Consultation_Needed"
]

In [24]:
df.dtypes

Patient_ID                      int64
Age                           float64
Gender                            str
Country                           str
Height_cm                     float64
Weight_kg                     float64
BMI                           float64
Waist_Circumference_cm        float64
Blood_Glucose                 float64
HbA1c                         float64
Fasting_Blood_Sugar           float64
Insulin_Level                 float64
Blood_Pressure_Systolic         int64
Blood_Pressure_Diastolic        int64
Total_Cholesterol             float64
HDL                           float64
LDL                           float64
Triglycerides                 float64
Heart_Rate                      int64
Physical_Activity_Level           str
Exercise_Hours_Per_Week       float64
Daily_Walking_Minutes         float64
Diet_Quality                      str
Sugar_Intake_Level                str
Sleep_Hours                   float64
Stress_Level                      str
Smoking_Status                    str
Alcohol_Consumption               str
Family_History_Diabetes           str
Hypertension                      str
Heart_Disease                     str
Fatty_Liver                       str
PCOS                              str
Medication_Adherence              str
Work_Type                         str
Residence_Type                    str
Daily_Water_Intake_L          float64
Diabetes_Risk_Score             int64
AI_Health_Recommendation          str
Doctor_Consultation_Needed        str
Diabetes_Risk                     str
dtype: object

In [28]:
df["Country"].value_counts()

Country
Malaysia          2083
Russia            2071
France            2068
China             2065
Canada            2050
United Kingdom    2037
Nigeria           2023
Indonesia         2011
Egypt             2010
Spain             2007
Mexico            1999
Germany           1999
South Korea       1997
South Africa      1996
Italy             1989
Turkey            1984
Japan             1983
India             1974
Bangladesh        1970
Brazil            1967
Pakistan          1959
Australia         1956
United States     1954
Argentina         1952
Saudi Arabia      1896
Name: count, dtype: int64

In [31]:
df["Country"].unique()

<StringArray>
[        'Mexico',   'Saudi Arabia',      'Argentina',  'United States',
      'Australia',     'Bangladesh',        'Germany',       'Malaysia',
         'France',      'Indonesia',         'Turkey',   'South Africa',
        'Nigeria',         'Canada',    'South Korea',          'Spain',
       'Pakistan',          'India',         'Russia',          'China',
          'Italy',          'Egypt', 'United Kingdom',         'Brazil',
          'Japan']
Length: 25, dtype: str

In [29]:
df["Diet_Quality"].value_counts()

Diet_Quality
Healthy    16882
Average    16644
Poor       16474
Name: count, dtype: int64

In [30]:
df["Physical_Activity_Level"].value_counts()

Physical_Activity_Level
Low         16693
High        16502
Moderate    16305
Name: count, dtype: int64

In [32]:
df["Gender"].value_counts()

Gender
Male      16718
Other     16677
Female    16605
Name: count, dtype: int64

In [33]:
df["Sugar_Intake_Level"].value_counts()

Sugar_Intake_Level
Low         16864
Moderate    16698
High        16438
Name: count, dtype: int64

In [34]:
numerical_features = [
    "Age",
    "Height_cm",
    "Weight_kg",
    "BMI",
    "Waist_Circumference_cm",
    "Blood_Glucose",
    "HbA1c",
    "Fasting_Blood_Sugar",
    "Insulin_Level",
    "Blood_Pressure_Systolic",
    "Blood_Pressure_Diastolic",
    "Total_Cholesterol",
    "HDL",
    "LDL",
    "Triglycerides",
    "Heart_Rate",
    "Exercise_Hours_Per_Week",
    "Daily_Walking_Minutes",
    "Sleep_Hours"
]


categorical_features = [
    "Gender",
    "Country",
    "Physical_Activity_Level",
    "Diet_Quality",
    "Sugar_Intake_Level"
]

In [35]:
df[numerical_features].isnull().sum()

Age                          497
Height_cm                   2945
Weight_kg                   2962
BMI                            0
Waist_Circumference_cm         0
Blood_Glucose                959
HbA1c                       1974
Fasting_Blood_Sugar            0
Insulin_Level                  0
Blood_Pressure_Systolic        0
Blood_Pressure_Diastolic       0
Total_Cholesterol           1000
HDL                         1000
LDL                         1000
Triglycerides               1000
Heart_Rate                     0
Exercise_Hours_Per_Week     1992
Daily_Walking_Minutes       1964
Sleep_Hours                 2017
dtype: int64

In [36]:
df[categorical_features].isnull().sum()

Gender                       0
Country                      0
Physical_Activity_Level    500
Diet_Quality                 0
Sugar_Intake_Level           0
dtype: int64

## Feature Classification

### Drop Features

- Patient_ID
- Diabetes_Risk_Score
- AI_Health_Recommendation
- Doctor_Consultation_Needed

### Numerical Features

- Age
- Height_cm
- Weight_kg
- BMI
- Waist_Circumference_cm
- Blood_Glucose
- HbA1c
- Fasting_Blood_Sugar
- Insulin_Level
- Blood_Pressure_Systolic
- Blood_Pressure_Diastolic
- Total_Cholesterol
- HDL
- LDL
- Triglycerides
- Heart_Rate
- Exercise_Hours_Per_Week
- Daily_Walking_Minutes
- Sleep_Hours


### Categorical Features

- Gender
- Country
- Physical_Activity_Level
- Diet_Quality
- Sugar_Intake_Level


### Target

- Diabetes_Risk

### Reason For Drop

- ID is meaningless
- Risk Scores are Data Leak
- AI Recommendation and Doctor Concultstion are Posterior Information